#cloud-config

users:
  - name: frank
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, root
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDqw5OrSh9kA5c7sZf8l+c1dNv1bbepxS0xknwCCWfoAaJBG208hfOLF+Mj7AeUCU+EefkbxyWtc6+57VZPv4nAR1hLryDrOtwSWF0/0JDO3Zhy/sS0Fbtn4V45L4RPyp/itYGWHR+bAODzOYHemeH638ObCQVmZ2voKtdlhDiMKzzGcHufPvph6xWM7BrlfW1Dr/OeGWQLC6hpM2MoqnJu+v3VcypbKNUGvVC2NN+uZc2X1oEPK0jJqNlUjutWBq+LVlAkvSAclFOLfleQhnYgdg6CxwE6rvIZQJ880L1vEmI6L0rPztSBQkhmgEyETGfm9v8w/7lkKEgUQmdWomgQM18oxRl4xw09iFKfo3p0RJaPedyHRZG/BWKdXmkw5CmVPZU/bLs3WMGT+k8q4mZf3+6DZDJDtepuDzp0DCe9Kn1ama5sc3GvwvwJK9BgHyMqxby5If1Hiz0LFs3WtxVVw77U5/OJ7AbiEV/3KMVgQchoA3wxPlDdc0NCUXf/ZxuLUXiuW+eULUo6k+PQffQh8bnKtYHkCZb2o7inOg29d7Y5baWMvm2N3yk3+14nNF8gbY7mFPYVdCNMtA7ex+Any98rZaejkjwBtzGgnNrrtg3RC8/BpN/kNhWxdAhNDeRG7UIl2pgF8NavW7c2+7H99tlcKEWvZdTDK1o68Z7Vlw== stefan_aws
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBtU9yMxnBW/YmRK002orz+POGfMTF8ZkRCHWfe9wHfc stefan+desktop-win10@fluit-online.nl
      - ssh-rsa ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDAQg+8wkxXbHwQilAKhyVqmskHjGIDktEBnmIIvvD84PzaX606JvHJI2/Yn9nAzZD9cRCb3G242H+l8aCxWVL1yUCOo/g1F87JzERxbQ45FN78n4GiKY//5hTcbSmsWR+CSUeWSQFW9m3WAhM9WfZbfZfPMXERdQT7EEGTNNSJvISTYfAAj/FwiXoVt3RBRgmkLxEEic0dLyM3pJtpCKRlZv41eHCSJ155T+UKVGTiMZW1UnSd+BstcBB30W/uWjM/mFvDlgQjjLUx4Ol7yvoT1ssLWdKPzhS8L+QmdrpX52rzgQuasjZ49BgwKl4lYRIwWeUT9WJv13aHzbdyENkQiX1a88hsjarSPnR/t+J6aaXczRhAvsirdcatsHwdv6bGrIHpvl5szi7Hya+L49Af8GL/bq+iKP83izqxabfbs2QPYrf9ftwBevSXXtQ+lMKgKAt/vOUfTH/XaUGQgJctCkChbdkuuCNYv56JK3z7g97D0xQ9/DLu/96DmIL/1cY7aNC0Pw18WeJu1E8Xme5jjbXNTBBtgNbB8trjuDaFzqP6060D2Mj2zosogPLHjPZcP72bUmHxQygyO+gFu9iG3heOS71Nzr/szL+TBs6Dt5HETA/iWsRz1jRfnEpAZfXLoNB9x7bvMXB8Uq0j5L444V/BmLPNEetWGliXMibljQ== frank@Frank-Desktop
      
package_update: true
package_upgrade: true

packages:
  - zsh
  - apt-transport-https
  - ca-certificates
  - curl
  - git
  - software-properties-common
  - python-is-python3
  - fonts-powerline
  - gnupg-agent
  - vim
  - mtr
  - wget

runcmd:
  # Configure ohmyzsh
  - runuser -l frank -c 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended'
  - runuser -l frank -c 'wget -O /home/frank/.zshrc https://raw.githubusercontent.com/stefanfluit/default_files/master/oh_my_zsh/.zshrc-pnd'
  - sed -i 's/empty-user/frank/g' /home/frank/.zshrc
  - chsh -s $(which zsh) frank
  # Change hostname
  - sudo hostnamectl set-hostname binance-collector