#cloud-config

users:
  - name: frank
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, root
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDqw5OrSh9kA5c7sZf8l+c1dNv1bbepxS0xknwCCWfoAaJBG208hfOLF+Mj7AeUCU+EefkbxyWtc6+57VZPv4nAR1hLryDrOtwSWF0/0JDO3Zhy/sS0Fbtn4V45L4RPyp/itYGWHR+bAODzOYHemeH638ObCQVmZ2voKtdlhDiMKzzGcHufPvph6xWM7BrlfW1Dr/OeGWQLC6hpM2MoqnJu+v3VcypbKNUGvVC2NN+uZc2X1oEPK0jJqNlUjutWBq+LVlAkvSAclFOLfleQhnYgdg6CxwE6rvIZQJ880L1vEmI6L0rPztSBQkhmgEyETGfm9v8w/7lkKEgUQmdWomgQM18oxRl4xw09iFKfo3p0RJaPedyHRZG/BWKdXmkw5CmVPZU/bLs3WMGT+k8q4mZf3+6DZDJDtepuDzp0DCe9Kn1ama5sc3GvwvwJK9BgHyMqxby5If1Hiz0LFs3WtxVVw77U5/OJ7AbiEV/3KMVgQchoA3wxPlDdc0NCUXf/ZxuLUXiuW+eULUo6k+PQffQh8bnKtYHkCZb2o7inOg29d7Y5baWMvm2N3yk3+14nNF8gbY7mFPYVdCNMtA7ex+Any98rZaejkjwBtzGgnNrrtg3RC8/BpN/kNhWxdAhNDeRG7UIl2pgF8NavW7c2+7H99tlcKEWvZdTDK1o68Z7Vlw== stefan_aws
      
package_update: true
package_upgrade: true

packages:
  - zsh
  - apt-transport-https
  - ca-certificates
  - curl
  - git
  - software-properties-common
  - python-is-python3
  - fonts-powerline
  - gnupg-agent
  - vim
  - mtr
  - wget

runcmd:
  # Configure ohmyzsh
  - runuser -l frank -c 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended'
  - runuser -l frank -c 'wget -O /home/frank/.zshrc https://raw.githubusercontent.com/stefanfluit/default_files/master/oh_my_zsh/.zshrc-pnd'
  - sed -i 's/empty-user/frank/g' /home/frank/.zshrc
  - chsh -s $(which zsh) frank
  # Change hostname
  - sudo hostnamectl set-hostname binance-collector